"""Generated minimal SchaleDB gift metadata.

Only fields required by gift affinity point calculations are retained here.
The student metadata developer tool rewrites this declaration atomically.
"""

from __future__ import annotations

from typing import NotRequired, TypedDict


class GiftMeta(TypedDict):
    id: int
    category: str
    tags: list[str]
    exp_value: int


GIFT_ITEMS: dict[int, GiftMeta] = {5000: {'id': 5000,
        'category': 'Favor',
        'tags': ['K', 'DV', 'aK', 'ap', 'Bo', 'cP', 'fT', 'Gv', 'gb', 'Ia'],
        'exp_value': 20},
 5001: {'id': 5001,
        'category': 'Favor',
        'tags': ['K', 'DV', 'aj', 'ap', 'Be', 'BI', 'CY', 'Eu', 'eD', 'en', 'Gj', 'hb', 'Ib'],
        'exp_value': 20},
 5002: {'id': 5002,
        'category': 'Favor',
        'tags': ['K', 'DV', 'aL', 'aQ', 'Bw', 'dw', 'Hr', 'HS'],
        'exp_value': 20},
 5003: {'id': 5003,
        'category': 'Favor',
        'tags': ['K',
                 'DV',
                 'BB',
                 'aq',
                 'Bj',
                 'Bu',
                 'CZ',
                 'eP',
                 'FS',
                 'Gl',
                 'He',
                 'HF',
                 'Hh',
                 'hy',
                 'hZ'],
        'exp_value': 20},
 5004: {'id': 5004,
        'category': 'Favor',
        'tags': ['K', 'DV', 'BB', 'aR', 'bA', 'BS', 'eB', 'Fz'],
        'exp_value': 20},
 5005: {'id': 5005,
        'category': 'Favor',
        'tags': ['K', 'DV', 'Bb', 'ar', 'BQ', 'FG', 'GA', 'Gk', 'GP', 'Gp', 'go', 'HO'],
        'exp_value': 20},
 5006: {'id': 5006,
        'category': 'Favor',
        'tags': ['K', 'DV', 'Bb', 'aS', 'Bz', 'Du', 'eR', 'Hz', 'IG'],
        'exp_value': 20},
 5007: {'id': 5007,
        'category': 'Favor',
        'tags': ['K', 'DV', 'Bb', 'as', 'BY', 'Df', 'el', 'Gi'],
        'exp_value': 20},
 5008: {'id': 5008,
        'category': 'Favor',
        'tags': ['K',
                 'DV',
                 'aJ',
                 'ao',
                 'By',
                 'bE',
                 'ce',
                 'EM',
                 'fX',
                 'fY',
                 'fZ',
                 'Gg',
                 'gY',
                 'Hd',
                 'HN'],
        'exp_value': 20},
 5009: {'id': 5009,
        'category': 'Favor',
        'tags': ['K', 'DV', 'BB', 'aT', 'bB', 'De', 'DL', 'ek', 'Hi'],
        'exp_value': 20},
 5010: {'id': 5010,
        'category': 'Favor',
        'tags': ['K', 'DV', 'al', 'at', 'ba', 'bG', 'dZ', 'gf', 'gi', 'hp', 'hQ'],
        'exp_value': 20},
 5011: {'id': 5011,
        'category': 'Favor',
        'tags': ['K', 'DV', 'aL', 'aR', 'BW', 'cG', 'Gb', 'HL', 'Hl', 'hq', 'hr', 'hz', 'IA'],
        'exp_value': 20},
 5012: {'id': 5012,
        'category': 'Favor',
        'tags': ['K', 'DV', 'aJ', 'as', 'Cz', 'Gi'],
        'exp_value': 20},
 5013: {'id': 5013, 'category': 'Favor', 'tags': ['K', 'DV', 'aJ', 'aP'], 'exp_value': 20},
 5014: {'id': 5014,
        'category': 'Favor',
        'tags': ['K', 'DV', 'aK', 'aU', 'bD', 'Bv'],
        'exp_value': 20},
 5015: {'id': 5015,
        'category': 'Favor',
        'tags': ['K', 'DV', 'BB', 'au', 'bd', 'Bu', 'fC', 'HU'],
        'exp_value': 20},
 5016: {'id': 5016,
        'category': 'Favor',
        'tags': ['K', 'DV', 'aj', 'aR', 'BJ', 'Ei', 'Gh', 'gp', 'IH'],
        'exp_value': 20},
 5017: {'id': 5017,
        'category': 'Favor',
        'tags': ['K',
                 'DV',
                 'ak',
                 'aV',
                 'Bf',
                 'cb',
                 'ci',
                 'cl',
                 'Ds',
                 'eQ',
                 'eq',
                 'FH',
                 'Gi',
                 'hl',
                 'Iu'],
        'exp_value': 20},
 5018: {'id': 5018,
        'category': 'Favor',
        'tags': ['K', 'DV', 'al', 'av', 'BH', 'BN', 'cf', 'gZ'],
        'exp_value': 20},
 5019: {'id': 5019,
        'category': 'Favor',
        'tags': ['K', 'DV', 'ak', 'aW', 'BF', 'BV', 'cA', 'Ev', 'fB', 'fg', 'ht'],
        'exp_value': 20},
 5020: {'id': 5020,
        'category': 'Favor',
        'tags': ['K',
                 'DV',
                 'al',
                 'aw',
                 'BR',
                 'Bs',
                 'Cy',
                 'cg',
                 'co',
                 'Dd',
                 'Di',
                 'DK',
                 'GO',
                 'Gv',
                 'GW',
                 'Hs',
                 'Ic',
                 'ID',
                 'II',
                 'Ii'],
        'exp_value': 20},
 5021: {'id': 5021,
        'category': 'Favor',
        'tags': ['K', 'DV', 'aM', 'aX', 'Br', 'fB', 'HV', 'hs', 'hT'],
        'exp_value': 20},
 5022: {'id': 5022,
        'category': 'Favor',
        'tags': ['K', 'DV', 'al', 'ax', 'bc', 'gg', 'Hq', 'HR', 'Ix'],
        'exp_value': 20},
 5023: {'id': 5023,
        'category': 'Favor',
        'tags': ['K', 'DV', 'BB', 'aY', 'cL', 'eT', 'Gm', 'gc', 'Hf', 'HG', 'IQ', 'Iq'],
        'exp_value': 20},
 5024: {'id': 5024,
        'category': 'Favor',
        'tags': ['K', 'DV', 'am', 'ay', 'BK', 'Dj', 'eg', 'Gc', 'Gs', 'GT', 'gF'],
        'exp_value': 20},
 5025: {'id': 5025,
        'category': 'Favor',
        'tags': ['K', 'DV', 'al', 'aZ', 'BP', 'BX', 'Ec', 'eB', 'IS', 'Is'],
        'exp_value': 20},
 5026: {'id': 5026,
        'category': 'Favor',
        'tags': ['K', 'DV', 'aJ', 'az', 'BT', 'cH', 'ER', 'fX', 'fY', 'fZ', 'Hd', 'ha', 'hB'],
        'exp_value': 20},
 5027: {'id': 5027,
        'category': 'Favor',
        'tags': ['K', 'DV', 'aM', 'az', 'BL', 'cM', 'fh', 'HA'],
        'exp_value': 20},
 5028: {'id': 5028,
        'category': 'Favor',
        'tags': ['K', 'DV', 'aN', 'av', 'DD', 'IP', 'Ip'],
        'exp_value': 20},
 5029: {'id': 5029,
        'category': 'Favor',
        'tags': ['K', 'DV', 'ak', 'av', 'BO', 'cn', 'fg', 'Gd', 'hj'],
        'exp_value': 20},
 5030: {'id': 5030,
        'category': 'Favor',
        'tags': ['K', 'DV', 'ak', 'aQ', 'ck', 'Ew', 'eh', 'ff', 'Id'],
        'exp_value': 20},
 5031: {'id': 5031,
        'category': 'Favor',
        'tags': ['K',
                 'DV',
                 'an',
                 'BA',
                 'BE',
                 'bf',
                 'cF',
                 'cK',
                 'DF',
                 'DT',
                 'EM',
                 'eg',
                 'em',
                 'Gt',
                 'gl',
                 'gM',
                 'Hg',
                 'HH',
                 'hk',
                 'hL',
                 'IT',
                 'It'],
        'exp_value': 20},
 5032: {'id': 5032,
        'category': 'Favor',
        'tags': ['K', 'DV', 'BB', 'Ba', 'DJ', 'ei', 'FE'],
        'exp_value': 20},
 5033: {'id': 5033,
        'category': 'Favor',
        'tags': ['K', 'DV', 'aO', 'Ba', 'bF', 'cj', 'DU', 'EP', 'fC', 'Gr', 'GS', 'Gu', 'GV', 'gk'],
        'exp_value': 20},
 5034: {'id': 5034, 'category': 'Favor', 'tags': ['K', 'DV', 'CX', 'Cx'], 'exp_value': 20},
 5998: {'id': 5998, 'category': 'Favor', 'tags': ['BC', 'Bc'], 'exp_value': 20},
 5999: {'id': 5999, 'category': 'Favor', 'tags': ['BC', 'Bc'], 'exp_value': 20},
 5100: {'id': 5100,
        'category': 'Favor',
        'tags': ['K',
                 'Dv',
                 'BC',
                 'aK',
                 'Bf',
                 'de',
                 'Di',
                 'dj',
                 'Ds',
                 'dF',
                 'EI',
                 'Ej',
                 'ek',
                 'eL',
                 'fT',
                 'ft',
                 'Gi',
                 'GJ',
                 'gb',
                 'gC',
                 'gc',
                 'gD',
                 'HN',
                 'Hn'],
        'exp_value': 60},
 5101: {'id': 5101,
        'category': 'Favor',
        'tags': ['K',
                 'Dv',
                 'BC',
                 'BB',
                 'Ez',
                 'eA',
                 'eQ',
                 'eq',
                 'FC',
                 'Fc',
                 'FT',
                 'Ft',
                 'Ge',
                 'GF',
                 'gE',
                 'gH',
                 'HB',
                 'Hb',
                 'Hi',
                 'HJ',
                 'HU',
                 'Hu',
                 'hc',
                 'hD',
                 'Iw',
                 'IX'],
        'exp_value': 60},
 5102: {'id': 5102,
        'category': 'Favor',
        'tags': ['K',
                 'Dv',
                 'BC',
                 'Bb',
                 'Be',
                 'dC',
                 'BF',
                 'dD',
                 'cA',
                 'dd',
                 'cH',
                 'DY',
                 'bD',
                 'dn',
                 'EN',
                 'En',
                 'eP',
                 'ep',
                 'FG',
                 'Fg',
                 'GA',
                 'Ga',
                 'GP',
                 'Gp',
                 'ge',
                 'gh',
                 'HO',
                 'Ho',
                 'Hr',
                 'HS',
                 'HV',
                 'Hv',
                 'hm',
                 'hN',
                 'hr',
                 'hS'],
        'exp_value': 60},
 5103: {'id': 5103,
        'category': 'Favor',
        'tags': ['K',
                 'Dv',
                 'BC',
                 'ak',
                 'Bf',
                 'de',
                 'Dc',
                 'dq',
                 'cL',
                 'do',
                 'CY',
                 'dc',
                 'cl',
                 'dA',
                 'bb',
                 'da',
                 'Ds',
                 'dF',
                 'EE',
                 'Ef',
                 'Ew',
                 'EX',
                 'eh',
                 'eI',
                 'fE',
                 'fe',
                 'fg',
                 'fH',
                 'Gd',
                 'GE',
                 'ga',
                 'gB',
                 'Hq',
                 'HR',
                 'hj',
                 'hK',
                 'ht',
                 'hU',
                 'IH',
                 'Ih',
                 'IT',
                 'It',
                 'Iv',
                 'IW'],
        'exp_value': 60},
 5104: {'id': 5104,
        'category': 'Favor',
        'tags': ['K',
                 'Dv',
                 'BC',
                 'aJ',
                 'BL',
                 'Dw',
                 'cF',
                 'dH',
                 'BQ',
                 'Dx',
                 'dW',
                 'dX',
                 'Ed',
                 'EF',
                 'EO',
                 'Eo',
                 'ET',
                 'Et',
                 'ER',
                 'Er',
                 'eE',
                 'ee',
                 'FF',
                 'Ff',
                 'fD',
                 'fd',
                 'fh',
                 'fI',
                 'fX',
                 'fx',
                 'fY',
                 'fy',
                 'fZ',
                 'fz',
                 'Gg',
                 'GH',
                 'Gl',
                 'GM',
                 'Gu',
                 'GV',
                 'gl',
                 'gM',
                 'gY',
                 'gy',
                 'Hd',
                 'HE',
                 'HM',
                 'Hm'],
        'exp_value': 60},
 5105: {'id': 5105,
        'category': 'Favor',
        'tags': ['K',
                 'Dv',
                 'BC',
                 'aL',
                 'De',
                 'dK',
                 'BP',
                 'ds',
                 'Bq',
                 'dh',
                 'bA',
                 'dB',
                 'ba',
                 'dR',
                 'DL',
                 'DZ',
                 'dZ',
                 'EB',
                 'eC',
                 'ec',
                 'FH',
                 'Fh',
                 'Fy',
                 'FZ',
                 'Fz',
                 'fA',
                 'ff',
                 'fG',
                 'Gf',
                 'GG',
                 'Gz',
                 'gA',
                 'gf',
                 'gi',
                 'gn',
                 'gO',
                 'hp',
                 'hQ',
                 'hz',
                 'IA',
                 'Iy',
                 'IZ'],
        'exp_value': 60},
 5106: {'id': 5106,
        'category': 'Favor',
        'tags': ['K',
                 'Dv',
                 'BC',
                 'an',
                 'Bj',
                 'dp',
                 'Cy',
                 'Dz',
                 'co',
                 'dr',
                 'DF',
                 'dk',
                 'CZ',
                 'dQ',
                 'DK',
                 'dS',
                 'ED',
                 'Ee',
                 'eB',
                 'eb',
                 'eg',
                 'eH',
                 'em',
                 'eN',
                 'eR',
                 'er',
                 'FP',
                 'FR',
                 'GA',
                 'Ga',
                 'Gk',
                 'GL',
                 'GO',
                 'Go',
                 'Gv',
                 'GW',
                 'gg',
                 'gj',
                 'go',
                 'gP',
                 'Hf',
                 'HG',
                 'Hg',
                 'HH',
                 'HK',
                 'Hk',
                 'Hs',
                 'HT',
                 'Hz',
                 'hA',
                 'hl',
                 'hM',
                 'II',
                 'Ii',
                 'IQ',
                 'Iq',
                 'Iu',
                 'IV'],
        'exp_value': 60},
 5107: {'id': 5107,
        'category': 'Favor',
        'tags': ['K',
                 'Dv',
                 'BC',
                 'aO',
                 'BP',
                 'ds',
                 'BY',
                 'dI',
                 'Cz',
                 'di',
                 'cf',
                 'dm',
                 'cP',
                 'dN',
                 'bc',
                 'df',
                 'bD',
                 'dn',
                 'Eh',
                 'EJ',
                 'EP',
                 'Ep',
                 'ES',
                 'Es',
                 'ei',
                 'eJ',
                 'el',
                 'eM',
                 'FI',
                 'Fi',
                 'fC',
                 'fc',
                 'gk',
                 'gL',
                 'gp',
                 'gQ',
                 'hy',
                 'hZ',
                 'IS',
                 'Is'],
        'exp_value': 60},
 5108: {'id': 5108,
        'category': 'Favor',
        'tags': ['K',
                 'Dv',
                 'BC',
                 'aN',
                 'Bo',
                 'dP',
                 'Ey',
                 'EZ',
                 'Gs',
                 'GT',
                 'He',
                 'HF',
                 'HW',
                 'Hw',
                 'IP',
                 'Ip'],
        'exp_value': 60},
 5109: {'id': 5109,
        'category': 'Favor',
        'tags': ['K',
                 'Dv',
                 'BC',
                 'am',
                 'cg',
                 'dg',
                 'DD',
                 'dE',
                 'Br',
                 'dM',
                 'BX',
                 'dG',
                 'dz',
                 'Eb',
                 'EA',
                 'EC',
                 'eD',
                 'ed',
                 'eS',
                 'es',
                 'eT',
                 'et',
                 'FS',
                 'Fs',
                 'Gc',
                 'GD',
                 'Gt',
                 'GU',
                 'gF',
                 'gI',
                 'HA',
                 'Ha',
                 'Hh',
                 'HI',
                 'Ic',
                 'ID',
                 'Id',
                 'IE',
                 'IF',
                 'If'],
        'exp_value': 60},
 5110: {'id': 5110,
        'category': 'Favor',
        'tags': ['K',
                 'Dv',
                 'BC',
                 'aM',
                 'BE',
                 'db',
                 'BR',
                 'dO',
                 'EM',
                 'Em',
                 'Ex',
                 'EY',
                 'fB',
                 'fb',
                 'ha',
                 'hB',
                 'hk',
                 'hL'],
        'exp_value': 60},
 5111: {'id': 5111,
        'category': 'Favor',
        'tags': ['K',
                 'Dv',
                 'BC',
                 'aj',
                 'Ei',
                 'EK',
                 'Eu',
                 'EV',
                 'eD',
                 'ed',
                 'en',
                 'eO',
                 'FE',
                 'Fe',
                 'Gh',
                 'GI',
                 'Gr',
                 'GS',
                 'hb',
                 'hC',
                 'Ib',
                 'IC'],
        'exp_value': 60},
 5112: {'id': 5112,
        'category': 'Favor',
        'tags': ['K',
                 'Dv',
                 'BC',
                 'al',
                 'BS',
                 'DX',
                 'Bv',
                 'dJ',
                 'cG',
                 'dl',
                 'DJ',
                 'Dy',
                 'BW',
                 'dL',
                 'EQ',
                 'Eq',
                 'Ev',
                 'EW',
                 'eB',
                 'eb',
                 'FD',
                 'Fd',
                 'fD',
                 'fd',
                 'fS',
                 'fs',
                 'Gb',
                 'GC',
                 'Gm',
                 'GN',
                 'gG',
                 'gJ',
                 'gZ',
                 'gz',
                 'HL',
                 'Hl',
                 'hq',
                 'hR',
                 'hs',
                 'hT',
                 'Ia',
                 'IB',
                 'IG',
                 'Ig',
                 'IR',
                 'Ir',
                 'Ix',
                 'IY'],
        'exp_value': 60},
 5996: {'id': 5996, 'category': 'Favor', 'tags': ['BC', 'Bc', 'ew'], 'exp_value': 60},
 5997: {'id': 5997, 'category': 'Favor', 'tags': ['BC', 'Bc', 'ew'], 'exp_value': 60}}
